// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ktT6xxjnsaUIBU4-kJf1s9NeWAqij3Y',
    appId: '1:596013733093:android:15dc83c8c3905664dc300c',
    messagingSenderId: '596013733093',
    projectId: 'memeco-d3897',
    storageBucket: 'memeco-d3897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrxm0zAwpxlLcD7lFtj4HQ2IoMt3RDKFM',
    appId: '1:596013733093:ios:5a05b1fe6bff3d34dc300c',
    messagingSenderId: '596013733093',
    projectId: 'memeco-d3897',
    storageBucket: 'memeco-d3897.appspot.com',
    androidClientId: '596013733093-08nn814klrjblrpdb6ofrcsh5tfvoul1.apps.googleusercontent.com',
    iosClientId: '596013733093-ta4rthdgqicgku3u4ro695898d6vtokm.apps.googleusercontent.com',
    iosBundleId: 'com.scarkov.memeco',
  );
}
