// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVk9_-UJh39uBDkpmEfsjb8VrDhjOBNr8',
    appId: '1:596013733093:web:9cf3e0b36ae37bd1dc300c',
    messagingSenderId: '596013733093',
    projectId: 'memeco-d3897',
    authDomain: 'memeco-d3897.firebaseapp.com',
    storageBucket: 'memeco-d3897.appspot.com',
    measurementId: 'G-9SM9CB7ZCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ktT6xxjnsaUIBU4-kJf1s9NeWAqij3Y',
    appId: '1:596013733093:android:b45ba34030b51819dc300c',
    messagingSenderId: '596013733093',
    projectId: 'memeco-d3897',
    storageBucket: 'memeco-d3897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrxm0zAwpxlLcD7lFtj4HQ2IoMt3RDKFM',
    appId: '1:596013733093:ios:6f72f014d26bb6bbdc300c',
    messagingSenderId: '596013733093',
    projectId: 'memeco-d3897',
    storageBucket: 'memeco-d3897.appspot.com',
    androidClientId:
        '596013733093-08nn814klrjblrpdb6ofrcsh5tfvoul1.apps.googleusercontent.com',
    iosClientId:
        '596013733093-7ntfd1jeq2jh8bpe3ad1j3q72rvrj90d.apps.googleusercontent.com',
    iosBundleId: 'com.scarkov.memeco',
  );
}
