name: memeco
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2
  flutter: 3.27.4

dependencies:
  auto_route: ^9.3.0+1
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  equatable: ^2.0.7
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  forui: ^0.9.1+1
  forui_assets: ^0.9.1
  gap: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  mixpanel_flutter: ^2.3.3
  recase: ^4.1.0
  sentry_flutter: ^8.13.2
  sentry_logging: ^8.13.2
  slang_flutter: ^4.4.0
  supabase_flutter: ^2.8.3
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^9.3.1
  bloc_devtools_extension:
    path: ../packages/bloc_devtools_extension
  build_runner: ^2.4.14
  flow_test:
    path: ../packages/flow_test
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  slang: ^4.4.1
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
